"""The value-normalising layer of preprocess.py.

TDD: preprocess.py is a skeleton, so every test here is expected to fail with
NotImplementedError until the layer is written. Nothing is generated by running
an implementation -- every number, unit and operator below is written out
literally from the contracts in preprocess.py and the verified ground truths in
REVIEW_FINDINGS.md, so a wrong parser cannot satisfy them by agreeing with
itself.
"""

import importlib.util
import json
import pathlib
import re

import pandas as pd
import pytest

_PATH = pathlib.Path(__file__).with_name("preprocess.py")
_SPEC = importlib.util.spec_from_file_location("preprocess", _PATH)
preprocess = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(preprocess)

# the keys of one parsed potency row, in the order the contract names them
ROW_KEYS = {
    "relation", "value", "value_high", "error", "unit", "unit_inherited",
    "concentration", "concentration_unit", "bioactivity_type", "fragment",
    "raw", "quarantine",
}

DOI_PREFIX = "https://doi.org/"
PUBMED_PREFIX = "https://pubmed.ncbi.nlm.nih.gov/"
PORTAL_PREFIX = "https://www.chemicalprobes.org/"

# a pandas NaN, not a python one: this is the value as_text() actually meets
PANDAS_NAN = pd.Series([1.0, None]).iloc[1]


def parsed(raw, potency=None):
    return preprocess.parse_potency_value(raw, potency)


def check_rows(raw, potency, expected):
    """Compare a parse against a list of {key: value}, one per expected row.

    Only the keys named in each dict are checked. The key 'quarantine_mentions'
    asserts the row is quarantined and that its reason contains a substring the
    docstring of quarantine_reason justifies, so rewording a reason is free.
    """
    rows = parsed(raw, potency)
    assert len(rows) == len(expected), (
        f"{raw!r} -> {len(rows)} rows, expected {len(expected)}: "
        f"{[r.get('value') for r in rows]}"
    )
    for i, (row, want) in enumerate(zip(rows, expected)):
        for key, value in want.items():
            if key == "quarantine_mentions":
                assert row["quarantine"], f"row {i} of {raw!r} is not quarantined"
                assert value in row["quarantine"].lower(), (
                    f"row {i} of {raw!r}: reason {row['quarantine']!r} "
                    f"does not mention {value!r}"
                )
            else:
                assert row[key] == value, (
                    f"row {i} of {raw!r}: {key} is {row[key]!r}, expected {value!r}"
                )


def a_row(**over):
    """One parsed row, clean, for calling quarantine_reason() directly."""
    row = {
        "relation": None, "value": 1.0, "value_high": None, "error": None,
        "unit": "nM", "unit_inherited": False, "concentration": None,
        "concentration_unit": None, "bioactivity_type": None,
        "fragment": "1 nM", "raw": "1 nM", "quarantine": None,
    }
    row.update(over)
    return row


def dose_triple(entry):
    """(value, unit, route) out of whatever shape parse_dose returns."""
    if isinstance(entry, dict):
        return entry.get("value"), entry.get("unit"), entry.get("route")
    value, unit, route = entry
    return value, unit, route


# ------------------------------------------------------------------ as_text


class TestAsText:
    @pytest.mark.parametrize("value", [None, float("nan"), PANDAS_NAN, "", "   ", "\t\n"])
    def test_nothing_here_is_the_empty_string(self, value):
        assert preprocess.as_text(value) == ""

    def test_a_nan_never_becomes_the_word_nan(self):
        # `value or ""` on a pandas NaN writes 'nan' into the file, which then
        # loads as a compound name
        assert preprocess.as_text(PANDAS_NAN) != "nan"
        assert preprocess.as_text(float("nan")) != "nan"

    @pytest.mark.parametrize("value, expected", [
        ("nM", "nM"),
        ("  nM ", "nM"),
        # 10 probe names carry unstripped whitespace
        ("CHEMBL3092538 ", "CHEMBL3092538"),
        (" (R)-Zinc-3573", "(R)-Zinc-3573"),
        ("\t0.06 nM\n", "0.06 nM"),
    ])
    def test_strips(self, value, expected):
        assert preprocess.as_text(value) == expected

    @pytest.mark.parametrize("value, expected", [(0, "0"), (16, "16"), (0.06, "0.06")])
    def test_numbers_become_their_own_text(self, value, expected):
        assert preprocess.as_text(value) == expected

    def test_zero_is_not_nothing(self):
        assert preprocess.as_text(0) != ""


# -------------------------------------------------------------- normalise_moa


class TestNormaliseMoa:
    @pytest.mark.parametrize("value, expected", [
        ("Inhibitor", "inhibitor"),
        ("Degrader (PROTAC)", "degrader (protac)"),
        ("  Inverse Agonist ", "inverse agonist"),
        ("Covalent Inhibitor", "covalent inhibitor"),
        # plural of a single mechanism
        ("Molecular Glues", "molecular glue"),
        # typo in the export
        ("Antagoinist, Degrader", "antagonist, degrader"),
    ])
    def test_spelling(self, value, expected):
        assert preprocess.normalise_moa(value) == expected

    @pytest.mark.parametrize("value, expected", [
        ("Allosteric Activator, Orthosteric Inhibitor",
         "allosteric activator, orthosteric inhibitor"),
        ("Degrader, CELMoD", "degrader, celmod"),
        ("degrader/inhibitor", "degrader/inhibitor"),
        ("inhibitor and degrader", "inhibitor and degrader"),
        ("Antagonist, Inverse Agonist, mix Agonist/Antagonist in vivo",
         "antagonist, inverse agonist, mix agonist/antagonist in vivo"),
    ])
    def test_several_mechanisms_keep_their_shape(self, value, expected):
        assert preprocess.normalise_moa(value) == expected

    def test_inner_whitespace_collapses(self):
        # moa is part of the bioactivity_group key and the FK is byte-exact, so
        # two spellings would split one group in two
        assert preprocess.normalise_moa("Inverse  Agonist") == "inverse agonist"
        assert (preprocess.normalise_moa("Inhibitor ")
                == preprocess.normalise_moa("Inhibitor"))

    def test_nothing_stays_nothing(self):
        assert not preprocess.normalise_moa("")
        assert not preprocess.normalise_moa(None)


# ---------------------------------------------------------- normalise_endpoint


class TestNormaliseEndpoint:
    @pytest.mark.parametrize("value, expected", [
        ("IC 50", "IC50"),
        ("EC 50", "EC50"),
        ("DC 50", "DC50"),
        ("GI 50", "GI50"),
        ("IC50 ", "IC50"),
        ("IC  50", "IC50"),
        ("INH", "% inhibition"),
    ])
    def test_spelling(self, value, expected):
        assert preprocess.normalise_endpoint(value) == expected

    @pytest.mark.parametrize("label", ["IC50", "EC50", "DC50", "GI50", "Dmax"])
    def test_canonical_labels_are_unchanged(self, label):
        assert preprocess.normalise_endpoint(label) == label

    @pytest.mark.parametrize("value", ["Not done", "not done", "", None])
    def test_no_endpoint_is_none(self, value):
        assert preprocess.normalise_endpoint(value) is None


class TestSplitEndpoints:
    def test_three_labels(self):
        assert preprocess.split_endpoints("DC50, Dmax, IC50") == ["DC50", "Dmax", "IC50"]

    def test_one_label(self):
        assert preprocess.split_endpoints("IC50") == ["IC50"]

    def test_elements_are_normalised(self):
        assert preprocess.split_endpoints("DC 50, Dmax") == ["DC50", "Dmax"]

    @pytest.mark.parametrize("value", ["", None, "Not done"])
    def test_nothing_gives_no_labels(self, value):
        assert preprocess.split_endpoints(value) == []


class TestAssignEndpoint:
    @pytest.mark.parametrize("fragment, expected", [
        ("63 nM (DC50)", "DC50"),
        ("90.8% (Dmax)", "Dmax"),
        ("52 nM (EC50)", "EC50"),
    ])
    def test_the_endpoint_the_fragment_names(self, fragment, expected):
        assert preprocess.assign_endpoint(fragment, "DC50, Dmax, EC50") == expected

    def test_never_the_joined_label(self):
        for fragment in ("63 nM (DC50)", "90.8% (Dmax)", "52 nM (EC50)"):
            assert (preprocess.assign_endpoint(fragment, "DC50, Dmax, EC50")
                    != "DC50, Dmax, EC50")

    def test_one_endpoint_is_the_answer_for_every_fragment(self):
        assert preprocess.assign_endpoint("0.06 nM", "IC50") == "IC50"
        assert preprocess.assign_endpoint("anything at all", "IC50") == "IC50"

    def test_a_label_without_parentheses_still_matches(self):
        assert preprocess.assign_endpoint("MEC1.5 16 nM", "MEC1.5, MEC2.0") == "MEC1.5"

    def test_none_when_the_fragment_names_none_of_them(self):
        assert preprocess.assign_endpoint("9.8", "pIC50, Dmax") is None

    def test_none_when_the_record_names_no_endpoint(self):
        assert preprocess.assign_endpoint("0.06 nM", None) is None
        assert preprocess.assign_endpoint("0.06 nM", "") is None


# --------------------------------------------------------------- canonical_unit


class TestCanonicalUnit:
    @pytest.mark.parametrize("text, expected", [
        ("nM", "nM"),
        ("0.06 nM", "nM"),
        ("16 ± 11 nM", "nM"),
        ("nmol/L", "nM"),
        ("uM", "uM"),
        ("µM", "uM"),
        ("μM", "uM"),
        ("umol/L", "uM"),
        ("µmol/L", "uM"),
        ("pM", "pM"),
        ("mM", "mM"),
        ("mmol/L", "mM"),
        ("mol/L", "M"),
        (" M", "M"),
        ("16 M", "M"),
        ("%", "%"),
        ("90.8%", "%"),
        ("99 % ", "%"),
        ("°C", "degC"),
        ("37 °C", "degC"),
        ("M−1 s−1", "M-1s-1"),
        ("M–1·s–1", "M-1s-1"),
        ("per M per sec", "M-1s-1"),
        ("8 h", "h"),
    ])
    def test_one_spelling_per_unit(self, text, expected):
        assert preprocess.canonical_unit(text) == expected

    @pytest.mark.parametrize("text", [
        "T790M", "L858R/T790M", "WT", "MV4;11", "MOLM-13", "BD1", "HCT-116",
        "(K)", "(H)", "(M)", "(T)", "(human)", "Helicase activity", "", None,
    ])
    def test_an_ambiguous_letter_inside_a_label_is_not_a_unit(self, text):
        # the M of T790M as molar was a factor of 10^9; a cell line (K) was a
        # temperature and a species label (H) an hour
        assert preprocess.canonical_unit(text) is None

    @pytest.mark.parametrize("text, expected", [
        ("85 nM (M)", "nM"),
        ("1 nM (K)", "nM"),
        ("7.8 nM (human)", "nM"),
        ("0.13 L858R/T790M nM", "nM"),
        ("6.66 uM (53)", "uM"),
    ])
    def test_the_real_unit_wins_over_the_trap(self, text, expected):
        assert preprocess.canonical_unit(text) == expected


# ----------------------------------------------------------------------- repair


class TestRepair:
    def test_a_space_inside_a_decimal(self):
        assert "0.69" in preprocess.repair("0. 69 nM")

    def test_a_decimal_comma(self):
        repaired = preprocess.repair("6,5 nM")
        assert "6.5" in repaired
        assert "," not in repaired

    def test_a_thousands_separator(self):
        assert "1100" in preprocess.repair("1,100 ± 200 M−1 s−1")
        assert "38200" in preprocess.repair("kinact/KI 38,200 M–1·s–1")

    def test_a_split_unit(self):
        assert re.search(r"85\s*nM", preprocess.repair("85n M"))

    @pytest.mark.parametrize("text, symbol, word", [
        ("up to 10 µM", "<", "up to"),
        ("below 1 µM", "<", "below"),
        ("about 50 nM", "~", "about"),
        ("around 1 µM", "~", "around"),
    ])
    def test_word_operators_become_symbols(self, text, symbol, word):
        # a censored value that loses its operator loads as an exact one
        repaired = preprocess.repair(text)
        assert symbol in repaired
        assert word not in repaired.lower()

    @pytest.mark.parametrize("text", [
        "0.06 nM",
        "< 1 nM",
        ">90",
        "IC50 = 493 ± 101 nM",
        "1 nM in MV4;11; 4 nM in MOLM-13",
        "MEC1.5 16 nM",
        "22-166 nM (T), 157 nM (A), 115 nM (B),  85 nM (M)",
        "14 WT,  2.2 T790M, 1.5 L858R, 0.13 L858R/T790M nM",
        "3.3 (human), 13 (rat) nM",
        "submicromolar",
    ])
    def test_leaves_alone_what_is_not_on_the_list(self, text):
        assert preprocess.repair(text) == text

    @pytest.mark.parametrize("text", [
        "0. 69 nM", "6,5 nM", "1,100 ± 200 M−1 s−1", "85n M",
        "up to 10 µM", "below 1 µM", "about 50 nM", "around 1 µM",
        "kinact/KI 38,200 M–1·s–1", "0.06 nM", "5-550nM",
    ])
    def test_idempotent(self, text):
        once = preprocess.repair(text)
        assert preprocess.repair(once) == once


# ------------------------------------------------------- split_value_fragments


def numeric_fragments(text):
    return [f for f in preprocess.split_value_fragments(text) if re.search(r"\d", f)]


class TestSplitValueFragments:
    @pytest.mark.parametrize("text, count", [
        ("0.06 nM", 1),
        ("16 ± 11 nM", 1),
        ("5-550nM", 1),
        ("MEC1.5 16 nM", 1),
        ("GAL4 LXRα 6.66 uM (53)", 1),
        # already repaired: the thousands separator is gone before splitting
        ("1100 ± 200 M−1 s−1", 1),
        ("BD1 85.5, BD2 220 nM", 2),
        ("3.3 (human), 13 (rat) nM", 2),
        ("760nM and 1000nM", 2),
        ("1 or 41 nM", 2),
        ("8.5 and 4.7 nM", 2),
        ("7.8 nM (human) 2.4 nM  (Mouse)", 2),
        ("9.8; 99 % ", 2),
        ("63 nM (DC50); 90.8% (Dmax); 52 nM (EC50)", 3),
        ("22-166 nM (T), 157 nM (A), 115 nM (B),  85 nM (M)", 4),
        ("14 WT,  2.2 T790M, 1.5 L858R, 0.13 L858R/T790M nM", 4),
    ])
    def test_one_fragment_per_measurement(self, text, count):
        assert len(numeric_fragments(text)) == count

    def test_a_semicolon_inside_a_cell_line_name_does_not_split(self):
        fragments = numeric_fragments("1 nM in MV4;11; 4 nM in MOLM-13")
        assert len(fragments) == 2
        assert any("MV4;11" in f for f in fragments)


# ------------------------------------------------------- parse_potency_value


class TestParsePotencyValue:
    def test_row_keys(self):
        row, = parsed("0.06 nM", "IC50")
        assert set(row) == ROW_KEYS

    def test_the_raw_string_is_kept_on_every_row(self):
        raw = "3.3 (human), 13 (rat) nM"
        for row in parsed(raw):
            assert row["raw"] == raw

    def test_the_fragment_says_which_number_this_is(self):
        # the label is the only place the species survives once the schema takes
        # no extra column
        first, second = parsed("3.3 (human), 13 (rat) nM")
        assert "human" in first["fragment"]
        assert "rat" in second["fragment"]

    def test_potency_is_optional(self):
        row, = parsed("0.06 nM")
        assert row["value"] == 0.06

    def test_a_clean_value_is_not_quarantined(self):
        row, = parsed("0.06 nM", "IC50")
        assert row["quarantine"] is None


# ------------------------------------------------------------ quarantine_reason


class TestQuarantineReason:
    @pytest.mark.parametrize("row, potency", [
        (a_row(), "IC50"),
        (a_row(), None),
        (a_row(value=99.0, unit="%"), "Dmax"),
        (a_row(value=22.0, value_high=166.0), "IC50"),
        (a_row(value=7.6, unit="-log(M)"), "pEC50"),
        (a_row(value=0.0, unit="%"), "% inhibition"),
    ])
    def test_a_readable_row_has_no_reason(self, row, potency):
        assert preprocess.quarantine_reason(row, potency, False, False) is None

    def test_a_factor_of_ten_to_the_n(self):
        reason = preprocess.quarantine_reason(a_row(), None, True, False)
        assert reason
        assert "factor" in reason.lower()

    @pytest.mark.parametrize("unit", ["M-1s-1", "min-1"])
    def test_a_reciprocal_rate_constant(self, unit):
        reason = preprocess.quarantine_reason(a_row(unit=unit), None, False, False)
        assert reason
        assert "rate" in reason.lower()

    def test_two_numbers_behind_a_slash(self):
        reason = preprocess.quarantine_reason(a_row(value=98.0, unit="%"),
                                             "Dmax", False, True)
        assert reason
        assert "/" in reason

    @pytest.mark.parametrize("unit", ["h", "min"])
    def test_a_duration(self, unit):
        reason = preprocess.quarantine_reason(a_row(value=8.0, unit=unit),
                                             None, False, False)
        assert reason
        assert "duration" in reason.lower()

    def test_a_zero_molar_potency(self):
        reason = preprocess.quarantine_reason(a_row(value=0.0, unit="nM"),
                                             "IC50", False, False)
        assert reason
        assert "zero" in reason.lower()

    def test_an_implausible_molar_value(self):
        reason = preprocess.quarantine_reason(a_row(value=16.0, unit="M"),
                                             "EC50", False, False)
        assert reason
        assert "molar" in reason.lower()

    def test_a_range_that_reads_high_to_low(self):
        reason = preprocess.quarantine_reason(a_row(value=89.0, value_high=3.0, unit="%"),
                                              "activity", False, False)
        assert reason
        assert "range" in reason.lower()

    def test_a_p_scale_endpoint_with_a_molar_unit(self):
        reason = preprocess.quarantine_reason(a_row(value=7.6, unit="nM"),
                                             "pIC50", False, False)
        assert reason
        assert "scale" in reason.lower()


# ---------------------------------------------------------------- parse_dose


class TestParseDose:
    def test_one_dose(self):
        entries = preprocess.parse_dose("1 mg/Kg")
        assert len(entries) == 1
        value, unit, route = dose_triple(entries[0])
        assert value == 1.0
        assert unit == "mg/kg"
        assert not route

    def test_two_doses_by_two_routes(self):
        entries = preprocess.parse_dose("1 mg/Kg IV, 5 mg/Kg PO")
        assert len(entries) == 2
        first, second = (dose_triple(e) for e in entries)
        assert first == (1.0, "mg/kg", "IV")
        assert second == (5.0, "mg/kg", "PO")

    @pytest.mark.parametrize("raw", ["unknown", "", None])
    def test_no_dose(self, raw):
        assert preprocess.parse_dose(raw) == []

    @pytest.mark.parametrize("raw", ["1 mg/Kg", "1 mg/kg", "1 mgKg", "1 mpk"])
    def test_every_spelling_parses(self, raw):
        entries = preprocess.parse_dose(raw)
        assert len(entries) == 1
        value, unit, _ = dose_triple(entries[0])
        assert value == 1.0
        assert unit

    def test_the_unit_has_one_spelling(self):
        units = {dose_triple(preprocess.parse_dose(raw)[0])[1]
                 for raw in ("1 mg/Kg", "1 mg/kg", "1 mgKg", "1 mpk")}
        assert units == {"mg/kg"}


# ----------------------------------------------------------- reference_source


class TestReferenceSource:
    @pytest.mark.parametrize("value, xref_id, source_xref", [
        ("www.doi.org/10.1038/ncomms2304", DOI_PREFIX, "10.1038/ncomms2304"),
        ("https://doi.org/10.1021/jm051106d", DOI_PREFIX, "10.1021/jm051106d"),
        # the field is named after PubMed, so the id can be in three shapes
        ("http://www.ncbi.nlm.nih.gov/pubmed/23250418", PUBMED_PREFIX, "23250418"),
        ("https://pubmed.ncbi.nlm.nih.gov/22056746/", PUBMED_PREFIX, "22056746"),
        ("http://www.ncbi.nlm.nih.gov/pubmed/?term=26101569", PUBMED_PREFIX, "26101569"),
    ])
    def test_an_identifier_resolves_through_its_registry(self, value, xref_id, source_xref):
        assert preprocess.reference_source(value) == (xref_id, source_xref)

    @pytest.mark.parametrize("value, doi", [
        ("www.doi/org/10.1021/ml400496h", "10.1021/ml400496h"),
        ("www.di.org/10.1021/jm051106d", "10.1021/jm051106d"),
        ("www.doi/org/10.1038/s41589-018-0055-y", "10.1038/s41589-018-0055-y"),
    ])
    def test_the_three_malformed_hosts_still_give_a_doi(self, value, doi):
        assert preprocess.reference_source(value) == (DOI_PREFIX, doi)

    @pytest.mark.parametrize("url", [
        "http://cancerres.aacrjournals.org/content/58/6/1111.long",
        "http://advances.sciencemag.org/content/1/10/e1500723",
    ])
    def test_a_publisher_url_stays_whole_with_no_prefix(self, url):
        assert preprocess.reference_source(url) == (None, url)

    def test_the_prefixes_are_the_module_constants(self):
        assert preprocess.DOI_PREFIX == DOI_PREFIX
        assert preprocess.PUBMED_PREFIX == PUBMED_PREFIX
        assert (preprocess.reference_source("www.doi.org/10.1038/ncomms2304")[0]
                == preprocess.DOI_PREFIX)
        assert (preprocess.reference_source(
            "http://www.ncbi.nlm.nih.gov/pubmed/23250418")[0]
            == preprocess.PUBMED_PREFIX)


# -------------------------------------------------------------- portal_source


def portal_url_sample(n=24):
    """A deterministic sample of the real probe URLs, unsuitables included."""
    path = pathlib.Path(__file__).with_name("ChemicalProbesPortal-6_8_2026.json")
    if not path.exists():
        return []
    urls = sorted({p["URL"] for p in json.loads(path.read_text())["probes"] if p.get("URL")})
    if not urls:
        return []
    two_segments = [u for u in urls if u.count("/") > 3][:4]
    step = max(1, len(urls) // n)
    return sorted(set(urls[::step][:n]) | set(two_segments))


PORTAL_SAMPLE = portal_url_sample() or [
    pytest.param("", marks=pytest.mark.skip(reason="portal export not on disk"))
]


class TestPortalSource:
    def test_one_path_segment(self):
        assert (preprocess.portal_source("https://www.chemicalprobes.org/sgc0946")
                == (PORTAL_PREFIX, "sgc0946"))

    def test_two_path_segments(self):
        # the 260 unsuitable probes live under /unsuitables/ and dropping that
        # builds a 404
        assert (preprocess.portal_source(
            "https://www.chemicalprobes.org/unsuitables/jib-04")
            == (PORTAL_PREFIX, "unsuitables/jib-04"))

    def test_the_prefix_is_the_module_constant(self):
        assert preprocess.PORTAL_PREFIX == PORTAL_PREFIX
        assert (preprocess.portal_source("https://www.chemicalprobes.org/sgc0946")[0]
                == preprocess.PORTAL_PREFIX)

    @pytest.mark.parametrize("url", PORTAL_SAMPLE)
    def test_prefix_plus_path_rebuilds_the_url(self, url):
        xref_id, path = preprocess.portal_source(url)
        assert xref_id + path == url


# ==================================================================== regressions
#
# Every case below is a defect an adversarial pass over all 3551 records found in
# the first parser, or a trap it was verified not to fall into. The comment on
# each says what used to happen. REVIEW_FINDINGS.md section 1 is the record.

REGRESSIONS = [
    # baseline: a plain value stays plain and is not quarantined
    pytest.param("0.06 nM", None, [
        {"relation": None, "value": 0.06, "value_high": None, "error": None,
         "unit": "nM", "unit_inherited": False, "concentration": None,
         "concentration_unit": None, "quarantine": None},
    ], id="0.06 nM"),

    # a censored value must never load as exact: the operator was dropped
    pytest.param("< 1 nM", "IC50", [
        {"relation": "<", "value": 1.0, "unit": "nM"},
    ], id="< 1 nM"),
    pytest.param("up to 10 µM", "IC50", [
        {"relation": "<", "value": 10.0, "unit": "uM"},
    ], id="up to 10 uM"),
    pytest.param("below 1 µM", "Activity", [
        {"relation": "<", "value": 1.0, "unit": "uM"},
    ], id="below 1 uM"),
    pytest.param("about 50 nM", None, [
        {"relation": "~", "value": 50.0, "unit": "nM"},
    ], id="about 50 nM"),
    pytest.param("around 1 µM", None, [
        {"relation": "~", "value": 1.0, "unit": "uM"},
    ], id="around 1 uM"),

    # relation NULL: the '=' branch of the regex was unreachable, 8 records
    pytest.param("IC50 = 493 ± 101 nM", "IC50", [
        {"relation": "=", "value": 493.0, "error": 101.0, "unit": "nM"},
    ], id="IC50 = 493 +- 101 nM"),
    pytest.param("16 ± 11 nM", None, [
        {"value": 16.0, "error": 11.0, "unit": "nM"},
    ], id="16 +- 11 nM"),

    # a space inside the decimal read as 0.0
    pytest.param("0. 69 nM", "IC50", [
        {"value": 0.69, "unit": "nM"},
    ], id="0. 69 nM"),

    # a european decimal comma split into two rows, 6 and 5
    pytest.param("6,5 nM", "GI50", [
        {"value": 6.5, "unit": "nM"},
    ], id="6,5 nM"),

    # a thousands separator, and the unit read as plain M
    pytest.param("1,100 ± 200 M−1 s−1", None, [
        {"value": 1100.0, "error": 200.0, "unit": "M-1s-1",
         "quarantine_mentions": "rate"},
    ], id="1,100 +- 200 M-1 s-1"),

    # 85 M -- wrong by a factor of 10^9
    pytest.param("85n M", None, [
        {"value": 85.0, "unit": "nM"},
    ], id="85n M"),

    # the M of T790M matched before the real nM and then propagated to the
    # unitless siblings: four values in M instead of nM
    pytest.param("14 WT,  2.2 T790M, 1.5 L858R, 0.13 L858R/T790M nM", None, [
        {"value": 14.0, "unit": "nM"},
        {"value": 2.2, "unit": "nM"},
        {"value": 1.5, "unit": "nM"},
        {"value": 0.13, "unit": "nM"},
    ], id="14 WT, 2.2 T790M, 1.5 L858R, 0.13 L858R/T790M nM"),

    # the upper bound of a range was lost
    pytest.param("5-550nM", "IC50", [
        {"value": 5.0, "value_high": 550.0, "unit": "nM"},
    ], id="5-550nM"),
    pytest.param("22-166 nM (T), 157 nM (A), 115 nM (B),  85 nM (M)", "IC50", [
        {"value": 22.0, "value_high": 166.0, "unit": "nM"},
        {"value": 157.0, "unit": "nM"},
        {"value": 115.0, "unit": "nM"},
        # the last label is (M): a trap for the molar guard
        {"value": 85.0, "unit": "nM"},
    ], id="22-166 nM (T), 157 nM (A), 115 nM (B), 85 nM (M)"),

    # the ';' inside the cell line name MV4;11 split one measurement in two
    pytest.param("1 nM in MV4;11; 4 nM in MOLM-13", "IC50", [
        {"value": 1.0, "unit": "nM"},
        {"value": 4.0, "unit": "nM"},
    ], id="1 nM in MV4;11; 4 nM in MOLM-13"),

    # numbers glued to the domain labels BD1/BD2 must not become values, and the
    # trailing unit is inherited by the fragment that has none
    pytest.param("BD1 85.5, BD2 220 nM", None, [
        {"value": 85.5, "unit": "nM", "unit_inherited": True},
        {"value": 220.0, "unit": "nM", "unit_inherited": False},
    ], id="BD1 85.5, BD2 220 nM"),
    pytest.param("3.3 (human), 13 (rat) nM", None, [
        {"value": 3.3, "unit": "nM"},
        {"value": 13.0, "unit": "nM"},
    ], id="3.3 (human), 13 (rat) nM"),

    # a record naming several endpoints must not propagate a unit: the 9.8 is a
    # pIC50 and inherited the '%' of the Dmax beside it
    pytest.param("9.8; 99 % ", "pIC50, Dmax", [
        {"value": 9.8, "unit_inherited": False},
        {"value": 99.0, "unit": "%"},
    ], id="9.8; 99 %"),

    # all three rows carried the comma-joined label 'DC50, Dmax, EC50'
    pytest.param("63 nM (DC50); 90.8% (Dmax); 52 nM (EC50)", "DC50, Dmax, EC50", [
        {"value": 63.0, "unit": "nM", "bioactivity_type": "DC50"},
        {"value": 90.8, "unit": "%", "bioactivity_type": "Dmax"},
        {"value": 52.0, "unit": "nM", "bioactivity_type": "EC50"},
    ], id="63 nM (DC50); 90.8% (Dmax); 52 nM (EC50)"),

    # a digit inside a label read as the value: 1.5 of MEC1.5, 4 of GAL4
    pytest.param("MEC1.5 16 nM", "MEC1.5, MEC2.0", [
        {"value": 16.0, "unit": "nM"},
    ], id="MEC1.5 16 nM"),
    pytest.param("GAL4 LXRα 6.66 uM (53)", "EC50 , (% effect)", [
        {"value": 6.66, "unit": "uM"},
    ], id="GAL4 LXRa 6.66 uM (53)"),

    # the unit came from the assay concentration, so 50 % loaded as 50 uM
    pytest.param("~50 at 3 uM", "% in", [
        {"relation": "~", "value": 50.0, "unit": "%",
         "concentration": 3.0, "concentration_unit": "uM"},
    ], id="~50 at 3 uM"),
    pytest.param("6.1 nM @ 10 uM ATP", "IC50", [
        {"value": 6.1, "unit": "nM", "concentration": 10.0,
         "concentration_unit": "uM"},
    ], id="6.1 nM @ 10 uM ATP"),

    # a unitless number whose scale is only in the endpoint label
    pytest.param("7.6", "pEC50", [
        {"value": 7.6, "unit": "-log(M)", "quarantine": None},
    ], id="7.6 pEC50"),
    pytest.param(">90", "% in", [
        {"relation": ">", "value": 90.0, "unit": "%"},
    ], id=">90 % in"),

    # the second measurement was dropped
    pytest.param("760nM and 1000nM", "EC50", [
        {"value": 760.0, "unit": "nM"},
        {"value": 1000.0, "unit": "nM"},
    ], id="760nM and 1000nM"),
    pytest.param("8.5 and 4.7 nM", "IC50", [
        {"value": 8.5, "unit": "nM"},
        {"value": 4.7, "unit": "nM"},
    ], id="8.5 and 4.7 nM"),
    pytest.param("1 or 41 nM", None, [
        {"value": 1.0, "unit": "nM"},
        {"value": 41.0, "unit": "nM"},
    ], id="1 or 41 nM"),
    pytest.param("7.8 nM (human) 2.4 nM  (Mouse)", None, [
        {"value": 7.8, "unit": "nM"},
        {"value": 2.4, "unit": "nM"},
    ], id="7.8 nM (human) 2.4 nM (Mouse)"),

    # quarantined rather than guessed
    pytest.param("16 M", "EC50", [
        {"value": 16.0, "unit": "M", "quarantine_mentions": "molar"},
    ], id="16 M"),
    pytest.param("kinact/KI 38,200 M–1·s–1", None, [
        {"unit": "M-1s-1", "quarantine_mentions": "rate"},
    ], id="kinact/KI 38,200 M-1.s-1"),
    pytest.param("98/100%", "Dmax", [
        {"value": 98.0, "quarantine_mentions": "/"},
    ], id="98/100%"),
    pytest.param("18/36 nM Hi/Lo ATP", None, [
        {"value": 18.0, "quarantine_mentions": "/"},
    ], id="18/36 nM Hi/Lo ATP"),
    pytest.param("10 nM to 1 µM", "INH", [
        {"value": 10.0, "value_high": 1.0, "quarantine_mentions": "range"},
    ], id="10 nM to 1 uM"),
    pytest.param("89-3% residual activity", "Activity", [
        {"value": 89.0, "value_high": 3.0, "unit": "%",
         "quarantine_mentions": "range"},
    ], id="89-3% residual activity"),
]


class TestReviewRegressions:
    @pytest.mark.parametrize("raw, potency, expected", REGRESSIONS)
    def test_regression(self, raw, potency, expected):
        check_rows(raw, potency, expected)

    # a factor of 10^n is never applied silently, so the row is held back
    def test_a_scientific_notation_factor_is_quarantined(self):
        for row in parsed("7.69 x 10^4 per M per sec"):
            assert row["quarantine"]

    # text with no number used to produce a fabricated row
    @pytest.mark.parametrize("raw", [
        "submicromolar", "low uM", "NA", "Helicase activity", "", None,
    ])
    def test_no_number_means_no_row(self, raw):
        assert parsed(raw) == []

    # the '%' of the Dmax beside it: 9.8 is a pIC50 and 9.8 % is meaningless
    def test_a_multi_endpoint_record_does_not_propagate_a_unit(self):
        first, _ = parsed("9.8; 99 % ", "pIC50, Dmax")
        assert first["unit"] != "%"

    # every row carried the comma-joined label of all three endpoints
    def test_the_joined_endpoint_label_never_reaches_a_row(self):
        rows = parsed("63 nM (DC50); 90.8% (Dmax); 52 nM (EC50)", "DC50, Dmax, EC50")
        for row in rows:
            assert row["bioactivity_type"] != "DC50, Dmax, EC50"

    # 0.0 instead of 0.69, which reads as a stronger probe than it is
    def test_a_split_decimal_is_not_zero(self):
        row, = parsed("0. 69 nM", "IC50")
        assert row["value"] != 0.0

    # a censored bound loading as an exact value is the worst failure mode here
    @pytest.mark.parametrize("raw", ["up to 10 µM", "below 1 µM", "< 1 nM"])
    def test_a_censored_value_is_never_exact(self, raw):
        row, = parsed(raw, "IC50")
        assert row["relation"] == "<"

    # a cell line called (K) was a temperature and a species label (H) an hour
    @pytest.mark.parametrize("raw, unit", [
        ("22-166 nM (T), 157 nM (A), 115 nM (B),  85 nM (M)", "nM"),
        ("7.8 nM (human) 2.4 nM  (Mouse)", "nM"),
    ])
    def test_a_parenthesised_label_is_not_a_unit(self, raw, unit):
        for row in parsed(raw, None):
            assert row["unit"] == unit

    # a parenthesised time window still reads as a measurement, so the row it
    # yields has to be caught by the duration rule rather than loaded
    def test_a_time_window_is_never_a_potency(self):
        rows = parsed("15 nM; (32 - 46 nM, 0 - 8 h)", None)
        assert rows[0]["value"] == 15.0
        assert rows[0]["unit"] == "nM"
        assert rows[0]["quarantine"] is None
        for row in rows:
            if row["unit"] in ("h", "min"):
                assert row["quarantine"]
                assert "duration" in row["quarantine"].lower()
